# Generated by Django 4.1.7 on 2023-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gpax',
            fields=[
                ('gpaxid', models.AutoField(db_column='GpaxID', primary_key=True, serialize=False)),
                ('gpax', models.FloatField(db_column='GPAX')),
            ],
            options={
                'db_table': 'gpax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('real_subject_id', models.CharField(max_length=200)),
                ('subject_name', models.CharField(max_length=200)),
                ('credit', models.IntegerField()),
                ('grade_char', models.CharField(max_length=200)),
                ('grade_int', models.FloatField()),
                ('year', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='gpa',
            options={'managed': False},
        ),
    ]
