# Generated by Django 4.1.7 on 2023-03-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_gpax_subjects_alter_gpa_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gpa',
            table='gpa',
        ),
    ]
