# Generated by Django 4.1.7 on 2023-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects_Test_Date',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('mid', models.CharField(max_length=255, null=True)),
                ('final', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
