# Generated by Django 4.1.7 on 2023-03-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_select', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects_test_date',
            options={'managed': True},
        ),
    ]
