# Generated by Django 4.1.7 on 2023-03-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_select', '0002_alter_subjects_test_date_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects_test_date',
            old_name='final',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='subjects_test_date',
            name='mid',
        ),
        migrations.AddField(
            model_name='subjects_test_date',
            name='credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subjects_test_date',
            name='fin_endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='subjects_test_date',
            name='fin_numday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subjects_test_date',
            name='fin_starttime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='subjects_test_date',
            name='mid_endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='subjects_test_date',
            name='mid_numday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subjects_test_date',
            name='mid_starttime',
            field=models.TimeField(null=True),
        ),
    ]
