# Generated by Django 4.1.7 on 2023-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects_info',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('subjects_name', models.CharField(max_length=255, null=True)),
                ('section', models.CharField(max_length=255, null=True)),
                ('day', models.CharField(max_length=255, null=True)),
                ('time', models.TimeField()),
                ('professor', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
