# Generated by Django 4.1.7 on 2023-03-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects_info',
            old_name='day',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='subjects_info',
            old_name='professor',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subjects_info',
            old_name='subjects_name',
            new_name='prof',
        ),
        migrations.RemoveField(
            model_name='subjects_info',
            name='time',
        ),
        migrations.AddField(
            model_name='subjects_info',
            name='credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subjects_info',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='subjects_info',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
