# Generated by Django 4.1.7 on 2023-03-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0003_user_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects_info',
            name='day',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
